### ISSUE TITLE
Half render and locks inputs after unlocking

### ISSUE THREAD

**Issue by Linkachus17** [hyprwm/hyprlock#427]
Almost same issue as #419 except there's nothing to do with pam, it's just half renders and sometimes locks my inputs after unlocking, have to enter another tty and return back to Hyprland to "unlock" my input.

Basically what happen with "locks my inputs" (if I look though the verbose) is that Hyprlock still renders the lock after unlocking, it did not unlock just yet after entering the password until I enter another tty and return to Hyprland, that's when Hyprlock unlocks itself

As for "Half render", Hyprlock first renders a red color (weirdly, because it never happened before), and then renders everything (background, text etc.) at like half transparency or else (because it's random). I either have to wait long time, or move my mouse to have the full render.
Verbose for both issue if you're curious: https://paste.linux.chat/?45b293a05fef521d#DiZPQwtmwCLNQa4iFa1DV2X3yiaRVr9NxZajsoNbXcFF

System specs:
Arch Linux 6.9.9-arch1-1
Ryzen 7 4800H
NVIDIA GTX1660Ti Mobile

**Comment by PaideiaDilemma** [comment]
hyprland and hyprlock versions?

**Comment by Linkachus17** [comment]
For Hyprland, I am running the latest git build 0.41.2 (manual build)
For Hyprlock, it's 0.4.0-2

**Comment by PaideiaDilemma** [comment]
> latest git build 0.41.2 (manual build)

so the tag v0.41.2, or latest commit?

**Comment by Linkachus17** [comment]
eh it should be latest commit because it's manual build, adding tag 0.41.2 because I am not sure what version my Hyprland is running

**Comment by PaideiaDilemma** [comment]
Yeah sorry hl git and hyprlock v0.4.0 (and below) don't work together since https://github.com/hyprwm/Hyprland/pull/6850. Should be fixed with #421.

Can you check hyprlock git please?

Also @vaxerski should we release 0.4.1 because of that?

**Comment by vaxerski** [comment]
we could, tag me tomorrow

**Comment by b0ch3nski** [comment]
@vaxerski tag :slightly_smiling_face:

**Comment by vaxerski** [comment]
https://github.com/hyprwm/hyprlock/releases/tag/v0.4.1

**Comment by MathisP75** [comment]
I am still facing this issue on 0.4.1. I get the reed flashbang every time hyprlock launches.

**Comment by PaideiaDilemma** [comment]
Hl version?

**Comment by Linkachus17** [comment]
Just wanted to say that the hyprlock-git 0.4.1.r17.g153977aa-1 fixed the issue. However the non-git version still broken

**Comment by MathisP75** [comment]
It's fixed for me on hyprland 0.44, aquamarine 0.4.1 and hyprlock 0.4.1.
